# Generated by Django 5.2.15 on 2026-07-25 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0013_appliedcorporateaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_encrypted', models.BinaryField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_chat_sessions', to='folioman_app.investor')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AgentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content_encrypted', models.BinaryField()),
                ('provider', models.CharField(default='local', max_length=16)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('data_as_of', models.DateField(blank=True, null=True)),
                ('pii_redactions', models.PositiveIntegerField(default=0)),
                ('external_transmission', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='folioman_app.agentchatsession')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='agentchatsession',
            index=models.Index(fields=['owned_by', 'investor', '-updated_at'], name='folioman_ap_owned_b_b2c758_idx'),
        ),
        migrations.AddIndex(
            model_name='agentchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='folioman_ap_session_51d36f_idx'),
        ),
    ]
